title: Platform Services
description: Discover and onboard to our AWS platform services

url: "https://bv90dsit.github.io"
baseurl: "/platform-services"

collections:
  services:
    output: true
    permalink: /services/:name/

defaults:
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: "_services"
      type: "services"
    values:
      layout: "default"
